// Use the client directive for using usePathname hook.
'use client';

import './globals.css';
import Navbar from './components/Navbar';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { usePathname } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className="bg-slate-800">
        {pathname !== '/blog' && pathname !== '/blog/posts/:postId' && <Navbar />}
        {children}
      </body>
    </html>
  );
}
